// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBook_Bingo.Migrations
{
    [DbContext(typeof(DataBook_BingoContext))]
    [Migration("20200602185617_initi")]
    partial class initi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataBook_Bingo.Models.Aldeia", b =>
                {
                    b.Property<int>("IdAldeia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImgAldeia")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NomeAldeia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisAldeia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAldeia");

                    b.ToTable("Aldeia");
                });

            modelBuilder.Entity("DataBook_Bingo.Models.Shinobi", b =>
                {
                    b.Property<int>("IdShinobi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Aldeia_Id")
                        .HasColumnType("int");

                    b.Property<string>("Cla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Membro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NomeShinobi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renegado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Vivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdShinobi");

                    b.HasIndex("Aldeia_Id");

                    b.ToTable("Shinobi");
                });

            modelBuilder.Entity("DataBook_Bingo.Models.Shinobi", b =>
                {
                    b.HasOne("DataBook_Bingo.Models.Aldeia", "Aldeia")
                        .WithMany()
                        .HasForeignKey("Aldeia_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
